version: "3.8"
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    working_dir: /srv/jekyll
    command: bash -lc "bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 8080 --livereload --livereload-port 35729 --watch --force_polling"
    ports:
      - "8080:8080"    # 사이트 접속
      - "35729:35729"  # 라이브리로드
    environment:
      JEKYLL_ENV: development
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle  # ★ Gem 캐시 영속화
    # build: .   # ← 프리빌트 이미지를 쓸 거면 이 줄은 주석/삭제
